import type { cargoOrder } from '@/models/cargo-related/order'
import { defineStore } from 'pinia'
export const useOrder = defineStore('orderStore', {
  state: (): cargoOrder => ({
    orderNumber: 0,
    client: 'sss',
    clientRefference: 'ss',
    loading: {
      name: 'Denicar',
      address: 'Nufarului',
      postalCode: '417495',
      city: 'Oradea',
      country: 'Romania',
      refferences: '12341',
      contacts: '0745',
      date: String(new Date().toISOString().split('T')[0]),
      time: '12:45',
    },
    delivery: {
      name: 'Denicar',
      address: 'Nufarului',
      postalCode: '417495',
      city: 'Oradea',
      country: 'Romania',
      refferences: '12341',
      contacts: '0745',
      date: String(new Date().toISOString().split('T')[0]),
      time: '12:45',
    },
    goods: [
      {
        type: '',
        number: 0,
        length: 0,
        width: 0,
        height: 0,
        weight: 0,
        stack: false,
      },
      {
        type: '',
        number: 0,
        length: 1,
        width: 0,
        height: 0,
        weight: 0,
        stack: false,
      },
      {
        type: '',
        number: 0,
        length: 0,
        width: 0,
        height: 0,
        weight: 0,
        stack: false,
      },
    ],
    observations: 'Nimic de reprosat sefu',
    currentCarrier: {
      number: 1,
      invoice: 'w2w2w',
      carrierName: 'DHL',
      contact: '07 nam cartela',
      plateNumber: '79DAG',
      driverName: 'Ghita',
      driverPhone: '00903333000',
      additionalInfoForOrder: 'nimic2',
      additionalInfoForUpdates: 'nimic2',
    },
    carriers: [
      {
        number: 1,
        invoice: 'wwww',
        carrierName: 'sss',
        contact: '',
        plateNumber: '',
        driverName: 'sss',
        driverPhone: '',
        additionalInfoForOrder: '',
        additionalInfoForUpdates: '',
      },
      {
        number: 2,
        invoice: 'ww',
        carrierName: '',
        contact: '',
        plateNumber: '',
        driverName: '',
        driverPhone: '',
        additionalInfoForOrder: '',
        additionalInfoForUpdates: '',
      },
    ],
  }),
})
