export interface carrierDbData{
  carrierName: string,
  contacts: string,
  driverName: string,
  driverPhoneNumber: string,
  invoiceNumber: string,
  obervationsForOrder: string,
  observationsForUpdates: string,
  orderNumber: number,
  plateNumber: string,
  highways: number,
  waiting: number,
  hotel: number,
  carrierPrice: number,
  totalCarrierPrice: number,
}
